services:
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crm
      MYSQL_USER: crm
      MYSQL_PASSWORD: crm
      MYSQL_ROOT_PASSWORD: root
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
